---
title: "ex-gimms"
author: "Dongdong Kong"
date: "2021/3/26"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown


```{r, fig.height=3}
library(phenofit)
# simulate vegetation time-series

df = read_xlsx("../data-raw/gimms_3pnts.xlsx")
sites = colnames(df)[-1]

tout = 1:365
for (site in sites) {
    # fFUN <- doubleLog.Beck
    # par <- c(mn = 0.1, mx = 0.7, sos = 50, rsp = 0.1, eos = 250, rau = 0.1)
    # t <- seq(1, 365, 8)
    # tout <- seq(1, 365, 1)
    # y <- fFUN(par, t)
    t = df$doy
    y = df[[site]]
    methods <- c("AG", "Beck", "Elmore", "Gu", "Zhang")[5] # "Klos" too slow
    fFITs <- curvefit(y, t, tout, methods)

    par(mfrow = c(1, 5),
        oma = c(1, 2, 3, 1), mar = rep(0, 4), yaxt = "n", xaxt = "n")
    # latticeGrob::write_fig({
    pheno <- get_pheno.fFITs(fFITs, "Zhang", IsPlot = TRUE)
    res = pheno %>% unlist()
    # }, "a.pdf")
}
```




```{r, fig.height=3}
library(phenofit)
library(glue)
# simulate vegetation time-series
# rm 

d = read_xlsx("data-raw/gimms_1pnt.xlsx")
# sites = colnames(df)[-1]
doy = d$doy[1:24]
date1 = as.Date(glue("2001-{doy}"), "%Y-%j")[1:24]
date2 = as.Date(glue("2002-{doy}"), "%Y-%j")[1:24]
date3 = as.Date(glue("2003-{doy}"), "%Y-%j")[1:24]
d$date <- c(date1, date2, date3)

INPUT <- check_input(d$date, d$y, nptperyear = 24)

wFUN = wTSM # wBisquare #
brks2 <- season_mov(INPUT,
    rFUN = smooth_wWHIT, wFUN = wFUN,
    calendarYear = TRUE, 
    plotdat = d, IsPlot = TRUE, IsPlot.OnlyBad = F, print = F)

fit  <- curvefits(INPUT, brks2,
                  methods = c("AG", "Zhang", "Beck", "Elmore"), #,"klos",, 'Gu'
                  wFUN = wFUN,
                  nextend = 2, maxExtendMonth = 3, minExtendMonth = 1, minPercValid = 0.2,
                  print = TRUE, verbose = FALSE)
library(ggplot2)
library(lubridate)
library(latticeGrob)
d_fit <- get_fitting(fit)
g <- plot_curvefits(d_fit, brks2, NULL, title.ylab = "NDVI", "Time",
                   theme = coord_cartesian(xlim = c(ymd("2000-04-01"), ymd("2017-07-31"))))
# grid::grid.newpage(); grid::grid.draw(g)# plot to check the curve fitting
write_fig(g, "a.pdf")

# param <- list(
#     INPUT, brks2,
#     methods = c("AG", "Zhang", "Beck", "Elmore", 'Gu'), #,"klos",
#     verbose = F,
#     wFUN = wFUN,
#     nextend = 2, maxExtendMonth = 2, minExtendMonth = 1,
#     minPercValid = 0.2,
#     print = FALSE
# )
# fit  <- do.call(curvefits, param)

tout = 1:365
for (site in sites) {
    # fFUN <- doubleLog.Beck
    # par <- c(mn = 0.1, mx = 0.7, sos = 50, rsp = 0.1, eos = 250, rau = 0.1)
    # t <- seq(1, 365, 8)
    # tout <- seq(1, 365, 1)
    # y <- fFUN(par, t)
    t = df$doy
    y = df[[site]]
    methods <- c("AG", "Beck", "Elmore", "Gu", "Zhang")[5] # "Klos" too slow
    fFITs <- curvefit(y, t, tout, methods)

    par(mfrow = c(1, 5),
        oma = c(1, 2, 3, 1), mar = rep(0, 4), yaxt = "n", xaxt = "n")
    # latticeGrob::write_fig({
    pheno <- get_pheno.fFITs(fFITs, "Zhang", IsPlot = TRUE)
    res = pheno %>% unlist()
    # }, "a.pdf")
}
```
